### ISSUE TITLE
Dataset without NIR data

### ISSUE THREAD

**Issue by mokby** [lyongo/NWPU-MOC#6]
I create my own datasets, but without NIR data. In `config.py`, line 18,  __C.MM= False, which says False means not using NIR data, I set False but when training, error occured.
```

Traceback (most recent call last):
  File "train.py", line 44, in <module>
    cc_trainer.forward()
  File "/data/qrs/NWPU-MOC/trainer.py", line 81, in forward
    self.train()
  File "/data/qrs/NWPU-MOC/trainer.py", line 112, in train
    for it, data in enumerate(self.train_loader, 0):
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1376, in _next_data
    return self._process_data(data)
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
    data.reraise()
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/qrs/NWPU-MOC/datasets/basedataset.py", line 71, in __getitem__
    rgb, nir, gt_map = self.read_data(index)
  File "/data/qrs/NWPU-MOC/datasets/basedataset.py", line 98, in read_data
    ir = Image.open(ir_path)
  File "/home/omnisky/anaconda3/envs/qi/lib/python3.8/site-packages/PIL/Image.py", line 3131, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/qrs/Datasets/MOC_pest/ir/1711873402463.jpg'
```
How can I training without NIR data? All I have is RGB images. Any help would be appreciated.

**Comment by mokby** [comment]
Solved, NIR is necessary in training, but in evaluation process NIR can be passed.

**Comment by cripsgreen** [comment]
Hello, may I ask how you created the NIR images? I would be very grateful if you could share the production process.
